name: Issue Test

on:
  pull_request:
    types: [ready_for_review, edited]

jobs:
  issue-test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: github.event.label.name == 'test-ci-version'
        uses: actions-cool/test-ci-version@v1
