name: Issue Test

on:
  issues:
    types: [labeled]

jobs:
  issue-test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: github.event.label.name == 'test-ci-version'
        uses: actions-cool/test-ci-version@v1.0.1
